import React, { PropsWithChildren } from 'react'

import Head from 'next/head'

import { centuryGothic, montserrat, ptSerif } from 'styles/fonts'

import { Footer } from './Footer'
import { Header } from './Header'

export const Layout = ({ children }: PropsWithChildren) => {
  return (
    <>
      <Head>
        <title>Furniture F</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png" />
        <link rel="manifest" href="/favicon/site.webmanifest" />
        <link rel="mask-icon" href="/favicon/safari-pinned-tab.svg" color="#5bbad5" />
        <meta name="msapplication-TileColor" content="#2b5797" />
        <meta name="theme-color" content="#ffffff" />
      </Head>
      <style jsx global>{`
        :root {
          --montserrat-font: ${montserrat.style.fontFamily};
          --ptSerif-font: ${ptSerif.style.fontFamily};
          --gothic-font: ${centuryGothic.style.fontFamily};
        }
      `}</style>
      <Header />
      {children}
      <Footer />
    </>
  )
}
